// @formatter:off
/* eslint-disable */
(function (window) {
/** @mixin */
var ds = window.ds;
if (!window.ds) ds = window.ds = {};
ds.types = {field: Field, pk: PrimaryKeyField, combined: Combined};

/** @type FieldExpression
* @constructor */
function Field() {}

/**@type FieldExpression
* @constructor */
function PrimaryKeyField() {}

/** @type ModelExpression
* @param modelName
* @constructor */
function Combined(modelName) {this.modelName = modelName;}

var f = new Field(),
p = new PrimaryKeyField(),
c = Combined;

ds.QSzFreight = {actualPayer: f,agentcyFeeType: f,agreementCurrency: f,agreementRate: f,allocatedAmount: f,allocationNo: f,allocationStatus: f,applyStatus: f,associatingCode: f,audit: f,auditBatchno: f,auditKtl: f,auditPerson: f,auditPersonName: f,auditTime: f,blType: f,bmsId: f,bmsUpDate: f,bmsUpFlag: f,bmsUpPerson: f,businessDate: f,businessTypeNo: f,carrierId: f,cashMovementNo: f,chargedDate: f,chargeWeight: f,cntCompany: f,cntNo: f,codesales: f,commisionId: f,commitTime: f,commitUserid: f,commitUsername: f,compId: f,completed: f,completeDate: f,completePerson: f,completePersonName: f,compStatus: f,confirmId: f,confirmNo: f,contactPerson: f,ctnSizeType: f,custId: f,custName: f,estimatedInvoiceType: f,estimatedTaxes: f,estimatedTaxRate: f,exchangeRate: f,exportDate: f,exportFlag: f,exportOffice: f,exportPersion: f,externalAccessSign: f,fileAmount: f,freightId: f,freightRate: f,freightSource: f,frtExport: f,frtId: f,frtMode: f,frtName: f,frtStype: f,frtType: f,innerRpFreightId: f,inputDate: f,inputOffice: f,inputPerson: f,inputPersonName: f,inputRole: f,invoiceAmount: f,invoiceId: f,invoiceNo: f,invoiceStatus: f,isCash: f,isCharged: f,isCommit: f,isContract: f,isEdiEpayOut: f,isFromQuotedprice: f,isInnerRp: f,isInput: f,isReplace: f,isSameprice: f,isVirSettle: f,isXt: f,itemType: f,jobOrderId: f,ledgerCurrency: f,ledgerRate: f,linkNo: f,masterItemId: f,modifyLastPerson: f,modifyLastTime: f,needAllocate: f,needAudit: f,needPrint: f,officeDept: f,opId: f,opName: f,orderNo: f,paymentNo: f,payStatus: f,payTerm: f,priceType: f,quantity: f,quoteAmount: f,quoteCurrency: f,quoteUnitPrice: f,rateToUsd: f,reCntrFreightId: f,reFreightId: f,remark: f,requestableAmount: f,requestAmount: f,requestId: f,requestNo: f,requestStatus: f,reSettlementId: f,rpId: f,rpPerson: f,rpPersonName: f,rpRelationId: f,rpStauts: f,salesAmount: f,salesCurrency: f,salesoffice: f,salesUnitPrice: f,settleAmount: f,settleCurrency: f,settleOffice: f,settlePlace: f,subKeyId: f,systemNo: f,taxFormula: f,testCount: f,timestamp: f,transactionDate: f,transactionOrderNo: f,unit: f,uniteNo: f,unitPrice: f,validDate: f,vesselAgencyId: f,virInvoiceNo: f,xchgRate: f,xtFreightId: f};
ds.QWaybillRouteNode = {arrivalSiteName: f,siteNum: f,startingSiteName: f,waybillId: f,waybillRouteNodeId:p};
ds.QWaybillInfo = {collectDatetime: f,collectEmployeeCname: f,collectEmployeeId: f,collectEmployeeMobile: f,consigneeCname: f,consigneeMobile: f,deliveryAddressDetail: f,deliveryAreaCode: f,productTypeCode: f,sendAddressDetail: f,sendAreaCode: f,shipperCname: f,shipperMobile: f,waybillId:p,waybillFee:new c("WaybillFee"),waybillRouteNodes:new c("WaybillRouteNode")};
ds.QSbCust = {active: f,addr: f,addrNative: f,applicationFormalDate: f,applicationFormalUser: f,applicationFormalUserName: f,applicationFrtDate: f,applicationFrtUser: f,applicationFrtUserName: f,approvedCustId: f,approvedCustName: f,belongFreight: f,blContent: f,blPrefix: f,businessNature: f,cityId: f,cityName: f,collectionPersonId: f,collectionPersonName: f,contact: f,countryId: f,creditAmt: f,creditCurrency: f,creditDays: f,creditInvalidationDate: f,creditNo: f,creditRemark: f,creditType: f,custAlias: f,custAliasCn: f,custId: f,custInnerOuter: f,custName: f,custNameNative: f,customsNo: f,custType: f,deleted: f,deletedReason: f,dragCtnPlace: f,dueType: f,ediCode: f,ein: f,email: f,endDate: f,fax: f,forward2Code: f,forwardCode: f,grade: f,homepage: f,idstring1: f,idstring2: f,idstring3: f,inputDate: f,inputOffice: f,inputOfficeCode: f,inputRole: f,inputUser: f,inputUserName: f,invAddr: f,invTitle: f,isCeInv: f,isCheckOrderOnline: f,isEdo: f,isOnline: f,isOoCarrier2: f,isProfit: f,isShowIzCust: f,ledgerCode: f,logic1: f,logic2: f,loginName: f,mdgBuGroup: f,mdgFaxExtens: f,mdgLangu: f,mdgMobNumber: f,mdgPartner: f,mdgRegion: f,mdgTelExtens: f,modidyUserName: f,modifyDate: f,modifyLastTime: f,modifyUser: f,needCargoTracking: f,pwd: f,registeredCapital: f,relateBussinessUser: f,relatedOffice: f,relateUser: f,remarkD: f,remCode: f,startDate: f,stateId: f,status: f,superiorId: f,superiorIdList: f,superiorName: f,taxNumber: f,taxRegisterNo: f,tel: f,unactive: f,vip: f,webProtocolEndDate: f,webProtocolNo: f,zip: f};
  ds.QDept = {
    deptId: p,
    deptName: f,
    principalGroupCode: f,
    information: f,
    textTest: f,
    longTextTest: f,
    employees: new c('Employee'),
  };
ds.QUserDeleteTest = {id:p,password: f,username: f};
ds.QUserExportTest = {id:p,password: f,username: f};
ds.QRpLedgerItem = {accountDissectionId: f,actualBaseCurrencyValue: f,actualInvoiceType: f,actualRateBase: f,actualTaxes: f,actualTaxRate: f,allocableBaseCurrencyValue: f,allocablePrimeCurrencyValue: f,allocableUsdValue: f,allocatedBaseCurrencyValue: f,allocatedPrimeCurrencyValue: f,allocatedUsdValue: f,allocationNo: f,applyBaseCurrencyCode: f,applyBaseCurrencyValue: f,applyPrimeCurrencyCode: f,applyPrimeCurrencyValue: f,applyUsdValue: f,approveBaseValue: f,approvePrimeValue: f,approveStatus: f,approveUsdValue: f,balanceTo: f,businessDate: f,businessId: f,cashMovementId: f,closeDate: f,collectBillDate: f,collectBillId: f,collectFlag: f,commissinAmount: f,commissionRate: f,compDate: f,compId: f,completeDate: f,completePerson: f,completePersonName: f,compNo: f,controlGlCoaCode: f,description: f,documentLocationReference: f,dueDate: f,estimatedInvoiceType: f,estimatedTaxes: f,estimatedTaxRate: f,externalPartnerCode: f,externalPartnerName: f,fiscalPeriod: f,freightInputDate: f,freightInputPerson: f,freightInputPersonName: f,glArpBusinessNo: f,glArpCoaCode: f,glArpFiscalPeriod: f,glArpVoucherId: f,glCostBusinessNo: f,glCostCoaCode: f,glCostFiscalPeriod: f,glCostVoucherId: f,glRateBase: f,glRateUsd: f,glTaxBusinessNo: f,glTaxFiscalPeriod: f,glTaxVoucherId: f,includeCommission: f,inputBatchNo: f,inputDate: f,inputOffice: f,inputPerson: f,inputPersonName: f,inputRole: f,invoiceBaseValue: f,invoiceNo: f,invoicePrimeValue: f,invoiceStatus: f,invoiceUsdValue: f,isCash: f,isInternal: f,isManual: f,isTaxDifference: f,itemType: f,ledgerItemId:p,ledgerItemStateInd: f,ledgerPartnerCode: f,ledgerPartnerName: f,ledgerTypeCode: f,linkNo: f,modifyLastTime: f,officeId: f,opId: f,opName: f,orderNo: f,payTerm: f,relatedArId: f,requestedBaseValue: f,requestedPrimeValue: f,requestedUsdValue: f,requestNo: f,requestStatus: f,reSettlementId: f,rpFrtId: f,rpFrtName: f,rpFrtStype: f,rpFrtType: f,rpId: f,rpPerson: f,rpPersonName: f,rpStauts: f,salesoffice: f,settlementRemarks: f,sourceId: f,sourceType: f,subTypeCode: f,subTypeCode2: f,systemType: f,taxFormula: f};
ds.QCsCust = {active: f,addrCn: f,addrEn: f,aicRegisteredNo: f,bizCsCustId: f,bizSystemType: f,cdhCode: f,cdhMaximum: f,cityCode: f,cityName: f,clientNo: f,countryCode: f,countryNameCn: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,csCustId:p,csFlag: f,custAlias: f,custCode: f,custNameCn: f,custNameEn: f,custOfficeCode: f,custOfficeName: f,customesRegisteredNo: f,custStatus: f,custType: f,defaultCollectionTerm: f,defaultPaymentTerm: f,email: f,expiryDate: f,fax: f,fictitiousPerson: f,importRemark: f,invalidName: f,invalidTime: f,invoiceMaximum: f,iqbRegisteredNo: f,isDeleted: f,isOneTimeCustomers: f,isSettlement: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,lndustryType: f,mdgCustCode: f,memoryCode: f,mobileNo: f,ownership: f,principalGroupCode: f,recordVersion: f,recoveryDate: f,registeredCapitqal: f,registeredDate: f,registeredTime: f,remarks: f,salesChannels: f,scale: f,settleCustCode: f,settleCustName: f,stakeProportion: f,stakeRelation: f,stateCode: f,stateName: f,subLndustryType: f,supplierFlag: f,taxNature: f,taxpayerIdentificatioNo: f,tel: f,type: f,unifiedCreditNo: f,vCdhCode: f,zip: f};
ds.QSbOffice = {abbrev: f,active: f,address: f,autoInternal: f,blContent: f,businessRegisterNo: f,cityId: f,cityName: f,companyId: f,contactId: f,countryId: f,custId: f,deleted: f,email: f,fax: f,functionType: f,homeCurrency: f,inputOffice: f,inputUser: f,inputUserName: f,isCustomer: f,isDept: f,isInternal: f,isSettlementObj: f,language: f,modifyLastTime: f,officeCode: f,officeId: f,officeName: f,officeNativeName: f,officeRelactionTag: f,officeType: f,settleOffice: f,superiorOfficeId: f,taxRegisterNo: f,tel: f,useSystem: f,xchgrName: f,zsjEntityEmpty: f,zsjOfficeId: f,zsjOfficeSid: f};
ds.QStudentNew = {address: f,age: f,birthday: f,confirmPassword: f,courseId: f,createTime: f,creator: f,email: f,enrollment: f,id:p,mobile: f,modifier: f,modifyTime: f,money: f,name: f,password: f,score: f,sex: f,teacherId: f,version: f};
ds.QUserImportTest = {id:p,password: f,username: f};
ds.QBcFreight = {actualBaseCurrencyValue: f,actualInvoiceType: f,actualRateBase: f,actualSettleCustCode: f,actualSettleCustName: f,actualTaxes: f,actualTaxRate: f,agreedPaymentDate: f,agreementCurrencyCode: f,agreementNo: f,agreementRate: f,allocableBaseCurrencyValue: f,allocablePrimeCurrencyValue: f,allocatedBaseCurrencyValue: f,allocatedPrimeCurrencyValue: f,allocationDate: f,allocationExchangeRate: f,allocationNo: f,allocationStatus: f,assignableAmount: f,attachmentFlag: f,auditDate: f,auditPersonCode: f,auditPersonName: f,auditStatus: f,baseCurrencyCode: f,baseCurrencyValue: f,bcAllocationEventId: f,bcChargeId: f,bcChequeId: f,bcFreightId:p,bcInvoiceId: f,bcLedgerCompId: f,bcPaymentRequestDocId: f,bcPaymentRequestId: f,bcPublicOrderId: f,bizReplaceId: f,bizSystemFreightId: f,bizSystemOrderId: f,bizSystemType: f,businessCode: f,businessName: f,businessOrderId: f,businessType: f,chargedDate: f,chargeExpression: f,chequeNo: f,cntId: f,cntNo: f,cntType: f,compNo: f,compNoBatch: f,compStatus: f,confirmNo: f,confirmStatus: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,deliveryJobNo: f,diffTaxes: f,diffTaxesArpFiscalPeriod: f,diffTaxesVoucherId: f,estimatedAmount: f,estimatedInvoiceType: f,estimatedInvoiceTypeName: f,estimatedTaxes: f,estimatedTaxRate: f,exchangeRate: f,feeRemark: f,freightBeginDate: f,freightCode: f,freightEndDate: f,freightNameCn: f,freightSource: f,freightType: f,frtBizTypeCode: f,frtBizTypeName: f,glArpFiscalPeriod: f,glRateBase: f,glVoucherDate: f,glVoucherId: f,hblNo: f,invoiceCode: f,invoiceNo: f,invoiceSerialNo: f,invoiceStatus: f,isCharged: f,isCommitGlVoucher: f,isDataCleaned: f,isDiffTaxes: f,isEdiEpayOut: f,isInternalFrt: f,isInvoice: f,isNotInvoice: f,isReplace: f,isSpot: f,isTax: f,isTaxFree: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,ledgerTypeCode: f,listNo: f,mblNo: f,noOfPeriod: f,payTerm: f,principalGroupCode: f,quantity: f,receivedStatus: f,recordVersion: f,remark: f,replaceId: f,replaceTypeCode: f,replaceTypeName: f,requestApproveStatus: f,requestNo: f,requestStatus: f,returnDepositNo: f,rpFlag: f,settleAmount: f,settleCurrencyCode: f,settleCustCode: f,settleCustDeptCode: f,settleCustDeptName: f,settleCustName: f,settlementRatio: f,settleOffice: f,settleOfficeDeptCode: f,settleOfficeDeptName: f,settleOfficeName: f,sourceCtnId: f,sourceFreightId: f,sourceOrderCtn: f,subOrderNo: f,taskCode: f,taskName: f,transferTaxes: f,unit: f,unitPrice: f,vehicleBrand: f,whCode: f,whName: f,writeoffId: f,writeoffStatus: f,writeoffType: f};
ds.QWaybillFee = {insuranceFee: f,totalFreight: f,volume: f,waybillId:p,weight: f};
ds.QSbCodedict = {bmsId: f,codeId: f,codeType: f,codeValue: f,displayValue: f,displayValueCn: f,modifiable: f,modifyLastTime: f,relateValue: f};
ds.QDictAreaInfoBak = {areaCode:p,areaFullName: f,areaShortName: f};
ds.QExportConfig = {async: f,className: f,columnSetting: f,dictionaryUrl: f,fileName: f,id:p,pageSize: f,printMode: f,sourceUrl: f,statisticsUrl: f,template: f};
ds.QMdFreightCode = {active: f,bizSystemId: f,bizSystemType: f,businessType: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,currency: f,feightGlobalName: f,freightCode: f,freightGlobalCode: f,freightNameCn: f,freightNameEn: f,freightType: f,invoiceFreightCode: f,invoiceName: f,isDeleted: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,mdFreightCodeId:p,memoryCode: f,principalGroupCode: f,recordVersion: f,remark: f,reportName: f,settleOffice: f,settleOfficeName: f,shortName: f};
ds.QChildren = {age: f,childName: f,createTime: f,creator: f,destroyed: f,englishName: f,enrollmentDate: f,giftCode: f,giftId: f,graduationDate: f,id:p,mailbox: f,mobile: f,modifier: f,modifyTime: f,parentsMobile: f,phone: f,schoolAge: f,sex: f,userAttribute: f,version: f};
ds.QI18nMessages = {id:p,key: f,localeId: f,message: f};
ds.QCourse = {courseContent: f,courseName: f,courseNum: f,createTime: f,creator: f,destroyed: f,id:p,modifier: f,modifyTime: f,userAttribute: f,version: f,student:new c("Student")};
ds.QUserAddTest = {id:p,password: f,username: f};
ds.QUserUpdateTest = {id:p,password: f,username: f};
ds.QTimerVersion = {identifier: f,modifyTime: f,timerId:p,version: f};
ds.QSupportedLocale = {country: f,display: f,id:p,language: f,state: f,variant: f};
ds.QBcPublicOrder = {acLockDate: f,acLockPersonCode: f,acLockPersonName: f,acLockStatus: f,auditDate: f,auditPersonCode: f,auditPersonName: f,auditStatus: f,bcPublicOrderId:p,berthingTime: f,bppCode: f,bppName: f,cimcId: f,cimcNo: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,discArea: f,feeRemark: f,flightNo: f,flowDirection: f,grossInterest: f,isIndependent: f,isInternalFrt: f,isNvocc: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,loadArea: f,mfLine: f,mfLineCode: f,parentOrderId: f,parentOrderNo: f,parentSubOrderId: f,parentSubOrderNo: f,paymentInterest: f,payTerm: f,payTypeCode: f,principalGroupCode: f,publicApprovalDate: f,publicApprovalFiscalPeriod: f,publicApprovalPersonCode: f,publicApprovalPersonName: f,publicApprovalRemark: f,publicAta: f,publicAtd: f,publicBizSystemType: f,publicBookingAgencyCode: f,publicBookingAgencyName: f,publicBookingProtocolNo: f,publicBusinessBegDate: f,publicBusinessDate: f,publicBusinessEndDate: f,publicBusinessFinishDate: f,publicBusinessOrderId: f,publicBusinessType: f,publicBusinessTypeName: f,publicCanvassionDepartment: f,publicCanvassionDeptCode: f,publicCanvassionMode: f,publicCargoDescriptionCn: f,publicCargoDescriptionEn: f,publicCarrierCode: f,publicCarrierName: f,publicChargingWeight: f,publicChargingWeightUnit: f,publicConsigneeCode: f,publicConsigneeName: f,publicConsignorCode: f,publicConsignorName: f,publicContactName: f,publicCooperatorOfficeCode: f,publicCooperatorOfficeName: f,publicCsCode: f,publicCsName: f,publicCtnNo: f,publicCtnNum: f,publicCtnTeu: f,publicCube: f,publicCubeUnit: f,publicCustBusinessNo: f,publicCustomNo: f,publicDestAgentCode: f,publicDestAgentName: f,publicEstimatedCompDate: f,publicEstimatedIssueDate: f,publicEta: f,publicEtd: f,publicFwPartnerCode: f,publicFwPartnerName: f,publicGoOrderId: f,publicGrossWeight: f,publicGrossWeightUnit: f,publicHblNo: f,publicIsApproval: f,publicIsCustomsClearance: f,publicIsHbl: f,publicIsInspection: f,publicIsInsurance: f,publicIsTruck: f,publicIsWarehouse: f,publicJobNo: f,publicMblNo: f,publicNoOfPackage: f,publicNotifyCode: f,publicNotifyName: f,publicOpCode: f,publicOperateType: f,publicOperateTypeName: f,publicOpName: f,publicOrderRemark: f,publicOrgId: f,publicOverseaOfficeCode: f,publicOverseaOfficeName: f,publicPackageType: f,publicPackageTypeName: f,publicPaymentMode: f,publicPod: f,publicPodCode: f,publicPol: f,publicPolCode: f,publicPortOfDestCode: f,publicPortOfDestination: f,publicProjectId: f,publicSalesCode: f,publicSalesName: f,publicSettleOffice: f,publicSettleOfficeName: f,publicShipperCode: f,publicShipperName: f,publicSourceType: f,publicSubBusinessType: f,publicTransportTerm: f,publicVesselCode: f,publicVesselName: f,publicVesselNameCn: f,publicVoyage: f,receiveInterest: f,recordVersion: f,smallSingleNo: f,voucherLockDate: f,voucherLockPersonCode: f,voucherLockPersonName: f,voucherLockStatus: f};
ds.QTeacher = {createTime: f,creator: f,destroyed: f,id:p,modifier: f,modifyTime: f,studentId: f,teacherAge: f,teacherName: f,userAttribute: f,version: f,sex: f};
ds.QStudent = {address: f,age: f,birthday: f,confirmPassword: f,courseId: f,createTime: f,creator: f,destroyed: f,email: f,enrollment: f,id:p,mobile: f,modifier: f,modifyTime: f,money: f,name: f,password: f,score: f,sex: f,teacherId: f,userAttribute: f,version: f,fileKey: f, teachers:new c("Teacher")};
ds.QRpPublicOrder = {azAgentName: f,azCarrierName: f,azConsigneeName: f,azEta: f,azEtd: f,azFlightNo: f,azIoInd: f,azNotifyName: f,azOperatorName: f,azOrderHbl: f,azSalesOfficeName: f,azServiceName: f,azShipperName: f,azSoourceMode: f,azSupplierName: f,cnCntNo: f,cnCntOperator: f,cnCntSealNo: f,cnCntSizetype: f,cnCntStatus: f,cnCntUserCode: f,cnDangerFlag: f,cnDeliveryPlace: f,cnDischargeArea: f,cnHaulierCode: f,cnIeFlag: f,cnJobType: f,cnLoadAreaCode: f,cnReturnPlace: f,cnSocFlag: f,huBerthingTime: f,huEtaTime: f,huEtdTime: f,huExpVoyageCode: f,huImpVoyageCode: f,huSailingTime: f,huShipCnName: f,inputCompanyId: f,inputDate: f,inputOfficeId: f,inputPerson: f,isNotax: f,modifyLastTime: f,ooAgentName: f,ooConsigneeName: f,ooCustOrderId: f,ooEta: f,ooEtd: f,ooFwPartnerId: f,ooFwPartnerName: f,ooHblNo: f,ooLinedefId: f,ooOperatorName: f,ooPrecarrierName: f,ooSalesOfficeName: f,ooServiceName: f,ooShipAgentName: f,ooShipperName: f,ooSourceMode: f,ooSourceModeName: f,publicBkNo: f,publicBlNo: f,publicBusinessDate: f,publicCompletedSign: f,publicConsignorFullname: f,publicConsignorName: f,publicContactName: f,publicCooperatorOfficeId: f,publicCooperatorOfficeName: f,publicCustomNo: f,publicDestinalPlace: f,publicJobNo: f,publicOrderId: f,publicOverseaOfficeId: f,publicOverseaOfficeName: f,publicPodName: f,publicPolName: f,publicSalesId: f,publicSalesName: f,publicSourceAgentId: f,publicSourceAgentName: f,publicVesselName: f,publicVesselNameCn: f,publicVoyage: f,refBusinessId: f,refBusinessType: f,refSystemType: f,seBookingParty: f,seCarrierName: f,seConsignee: f,seEtdTime: f,seLoadAreaCode: f,seMovementDisch: f,seMovementLoading: f,sePayTypeCode: f,seSailingTime: f,seSndEnVessel: f,seSndVoyageCode: f,siBerthingTime: f,siCarrierId: f,siCarrierName: f,siConsignee: f,siDiscAreaCode: f,siEtaTime: f,siImpVoyageCode: f,siLoadAreaCode: f,siMovementDischar: f,siMovementLoading: f,siPayTypeCode: f,siPreBlNo: f,siPreShipEnName: f,siPreVoyageNo: f};
ds.QShop = {giftShop: f,shopId:p,version: f,gifts:new c("Gift")};
ds.QGift = {createTime: f,creator: f,destroyed: f,giftCode: f,giftName: f,id:p,modifier: f,modifyTime: f,productionYear: f,shopId: f,userAttribute: f,version: f,children:new c("Children")};
ds.QUserSelectTest = {id:p,password: f,username: f};
ds.QEmployee = {address: f,age: f,birthDay: f,cname: f,createTime: f,creator: f,deptId: f,destroyed: f,email: f,employeeId:p,mobile: f,modifier: f,modifyTime: f,password: f,principalGroupCode: f,sex: f,username: f,version: f,dept:new c("Dept"),modifier:new c("Employee"),creator:new c("Employee")};
ds.QMdCodeDict = {active: f,codeType: f,codeValue: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,displayValue: f,displayValueCn: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,mdCodeDictId:p,mdCodeTypeId: f,principalGroupCode: f,recordVersion: f,relateValue: f,remark: f,serialNumber: f,settleOffice: f,settleOfficeName: f,tmpPId: f,tmpSeqId: f};
ds.QGlVoucher = {attachment: f,coaName: f,companyCode: f,companyName: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,departmentCode: f,externalVoucherNo: f,fiscalPeriod: f,glVoucherId:p,isDiffTaxes: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,principalGroupCode: f,profitCenter: f,recordVersion: f,referenceCode: f,seqNo: f,transactionNo: f,transactionSource: f,validateUser: f,validateUserName: f,voucherCategory: f,voucherDate: f,voucherExportPerson: f,voucherExportPersonName: f,voucherExportState: f,voucherExportTime: f,voucherNo: f,voucherRemarks: f,voucherState: f,voucherType: f};
ds.QImportConfig = {allowParameter: f,async: f,childrenTable: f,className: f,dealService: f,defineColumn: f,dictionaryUrl: f,id:p,methodName: f,primaryColumns: f,template: f,validateHead: f,validateMethod: f};
ds.QAppNodes = {appName: f,id:p,nodeName: f,nodeNum: f};
ds.QDictProductType = {productCode:p,productName: f};
ds.QMdGlobalBusiness = {active: f,createOffice: f,createTime: f,createTimeZone: f,creator: f,isDeleted: f,isTaxFree: f,lastModifyOffice: f,lastModifyor: f,lastModifyTime: f,lastModifyTimeZone: f,mdSubBusinessGlobalId:p,principalGroupCode: f,recordVersion: f,remark: f,subBusinessGlobalCode: f,subBusinessGlobalName: f};
ds.QChangeLog = {changeData: f,dataSourceId: f,id:p,modelName: f,operateTime: f,operator: f,sqlStmt: f};
ds.QDictAreaInfo = {areaCode:p,areaFullName: f,areaShortName: f};
ds.QGtxTrans = {gtxTransId:p,identifier: f,modifyTime: f,modifyTimeSec: f,participants: f,transName: f,tryCount: f,txCreateTime: f,txMode: f,txStatus: f,xid: f};
  ds.QMsgSmsConfig = {appKey: f,appSecret: f,businessSystemId: f,channelName: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,isDeleted: f,ispAccount: f,ispNo: f,ispPassword: f,isValid: f,keyword: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgSmsConfigId:p,priority: f,recordVersion: f,smsServiceType: f,smsUrl: f};
  ds.QAppNodes = {appName: f,id:p,nodeName: f,nodeNum: f};
  ds.QMsgSmsRecord = {businessSystemId: f,channelName: f,content: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,isDeleted: f,isSuccess: f,mobile: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgSmsRecordId:p,nationCode: f,reason: f,recordVersion: f,retryCount: f,smsTemplateCode: f,smsTemplateName: f,smsType: f};
  ds.QMsgEmailRecord = {attachmentUrl: f,businessSystemId: f,ccEmail: f,content: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,emailTemplateCode: f,emailTemplateName: f,isDeleted: f,isSuccess: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgEmailRecordId:p,reason: f,recordVersion: f,sendBatch: f,subject: f,toEmail: f};
  ds.QMsgEmailAttachment = {attachmentType: f,attachmentUrl: f,businessSystemId: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,isDeleted: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgEmailAttachmentId:p,msgEmailTemplateId: f,recordVersion: f};
  ds.QMsgSmsTemplate = {businessSystemId: f,content: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,description: f,isDeleted: f,isValid: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgSmsTemplateId:p,recordVersion: f,smsTemplateCode: f,smsTemplateName: f,smsType: f};
  ds.QMsgMarco = {businessSystemId: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,fieldName: f,isDeleted: f,isValid: f,marcoNameCn: f,marcoNameEn: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgMarcoId:p,recordVersion: f};
  ds.QMsgEmailTemplate = {businessSystemId: f,content: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,description: f,emailTemplateCode: f,emailTemplateName: f,isDeleted: f,isValid: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgEmailConfigId: f,msgEmailTemplateId:p,recordVersion: f,subject: f,msgEmailConfig:new c("MsgEmailConfig"),msgEmailAttachment:new c("MsgEmailAttachment")};
  ds.QMsgEmailConfig = {businessSystemId: f,createCompanyId: f,createCompanyName: f,createTime: f,creatorId: f,creatorName: f,emailAddress: f,emailConfigCode: f,emailConfigName: f,emailPassword: f,emailType: f,emailUser: f,host: f,isDeleted: f,isValid: f,modifierId: f,modifierName: f,modifyCompanyId: f,modifyCompanyName: f,modifyTime: f,msgEmailConfigId:p,port: f,protocol: f,recordVersion: f};
ds.QCtsIlpMdPort={mdPortId:f ,iataCode:f}
}(window));
// @formatter:on
